server:
  contextPath: /config-server-proxy
  port: 8888
  
security:
  user: my_user
  password: MySecret&23  
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: my_mq_user
    password: mq_secret_57*key
  cloud:
    config: 
      server:
        git:
          uri:        
          addLabelLocations: false
          searchPaths: /{application} 
          basedir: target/props-git-checkout