server:
  port: 8080
  servlet:
    contextPath: /reactive-demo
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/datasets
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
